### ISSUE TITLE
Using the attribute `logcat_regex` causes the experiment to crash

### ISSUE THREAD

**Issue by sshann** [S2-group/android-runner#39]
When defining the interaction script, Android Runner allows defining the attribute `logcat_regex` to filter the logs in Logcat.
However, doing so will crash the experiment or the interaction is skipped.

### Replication steps

The mobile device where the issue was encountered: Nexus 5X, Nexus 6P (Android 6.0)

Minimal configuration file example:
```json
{
  "type": "native",
  "scripts": {
    "after_launch": "scripts/after_launch.py",
    "interaction": [
      {
        "type": "python3",
        "path": "scripts/interaction/python3/interaction.py",
        "logcat_regex": "<expr>"
      }
    ],
    "before_close": "scripts/before_close.py"
  }
}
```

`interaction.py`
```python
import time


def main(device: Device, *args, **kwargs) -> None:
    print('Running interaction script')
    time.sleep(10)
    print('Finished')
```

Start an experiment

### Current issue

It is not possible to filter the Logcat logs using AR.
The filter is implemented at

https://github.com/S2-group/android-runner/blob/35ae4f6a313313e980608e75425639b9edeccae7/AndroidRunner/Adb.py#L142-L149

I tried to run the command directly via ADB the command below and got an error message `Unrecognized Option e`. 
Verifying the available options that my device has to access the Logcat via ADB, there is no option to filter the Logcat using regular expressions.

```
adb logcat -d -e <expr>
```

### Possible solutions

For my experiments, I found the following alternative:
```
adb logcat -d -s <my_tag>
```

This will filter the Logcat per tag.
To also filter by log message, another valid alternative is:

```
adb logcat -d | grep -e <expr>
```

I don't know if alternative 1 is compatible will all mobile devices.
Alternative 2 should be compatible with any device supporting logcat and any host machine supporting grep commands.

### Additional suggestions

In my experiment, I had to filter the Logcat using several different filters, each saved to a different file.
Instead of defining a single expression, it would be interesting to allow providing multiple filters.

**Comment by odmnk** [comment]
This issue is fixed by https://github.com/S2-group/android-runner/pull/76
