### ISSUE TITLE
Device.py command not working

### ISSUE THREAD

**Issue by umkhanqta** [S2-group/android-runner#50]
I am using android emulator on android studio
configuration of the emulator is 
NEXUS 6P, API 30
error shows in command
`adb shell dumpsys window windows'
 Not show mCurrentFocused | mFocusedApp in Device.py current_activity line#125, so use 
'adb shell dumpsys window displays'
is it OK?

**Comment by EricZielinski** [comment]
I also had issues with Device.py's current_activity method when using an emulator.  I added this line into the method to get it to work for my emulator:

`emulator_match_re = r'(?<=Window #6 Window{\S\S\S\S\S\S\S\s\S\S\s)(\D+)(?=\/)'`

I suggest adding a print statement below `windows = Adb.shell(self.id, 'dumpsys window windows')` to see what your dump looks like and you might be able to get away with using my solution or changing the #.

**Comment by umkhanqta** [comment]
Thankyou, it worked
