### ISSUE TITLE
getting error when running examples/trepn

### ISSUE THREAD

**Issue by umkhanqta** [S2-group/android-runner#52]
I am getting following error when running the command
`python3 android-runner android-runner/examples/trepn/config.json`
ExperimentFactory: /home/umair/Desktop/android-runner-master/android-runner/examples/trepn/config.json
NativeExperiment: Device: Nexus_6P_API_30 (emulator-5554, Android 11, API level 30)
Profilers: Loading
Device: Default unplug
Python3: before_experiment.py
Profilers: Setting output
NativeExperiment: Run 1/1 of subject "com.google.android.apps.messaging" on Nexus_6P_API_30
NativeExperiment: Logcat cleared
Python3: before_run.py
Python3: after_launch.py
Profilers: Start profiling
Python3: interaction.py
Profilers: Stop profiling
Python3: before_close.py
Python3: after_run.py
Profilers: Collecting results
NativeExperiment: Sleeping for 500 milliseconds
Profilers: Start subject aggregation
NativeExperiment: Experiment completed, start cleanup
Python3: after_experiment.py
Profilers: Stop profiling
Profilers: Unloading
Profilers: Start final aggregation
Python3: aggregate_trepn.py
Output file: /home/umair/Desktop/android-runner-master/android-runner/examples/trepn/output/2020.09.07_022123/Aggregated_Results_Trepn.csv
<csv.DictReader object at 0x7f00657a6828>
root: ScriptError: Error in aggregate_trepn.py: iterator should return strings, not bytes (did you open the file in text mode?)
Traceback (most recent call last):
  File "android-runner/AndroidRunner/Script.py", line 33, in mp_run
    output = self.execute_script(device, *args, **kwargs)
  File "android-runner/AndroidRunner/Python3.py", line 19, in execute_script
    return self.module.main(device, *args, **kwargs)
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/trepn/Scripts/aggregate_trepn.py", line 80, in main
    rows = aggregate(data_dir)
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/trepn/Scripts/aggregate_trepn.py", line 58, in aggregate
    row.update(aggregate_trepn_final(os.path.join(subject_dir, 'trepn')))
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/trepn/Scripts/aggregate_trepn.py", line 27, in aggregate_trepn_final
    column_readers = split_reader(reader)
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/trepn/Scripts/aggregate_trepn.py", line 41, in split_reader
    column_dicts = {fn: [] for fn in reader.fieldnames if not fn.split('[')[0].strip() == 'Time'}
  File "/usr/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

root: An error occurred, the experiment has been stopped. To continue, add progress file argument to experiment startup: --progress /home/umair/Desktop/android-runner-master/android-runner/examples/trepn/output/2020.09.07_022123/progress.xml

**Comment by EricZielinski** [comment]
Thanks.  Same solution as here: https://github.com/S2-group/android-runner/issues/49.

**Comment by umkhanqta** [comment]
yes, that is working
