### ISSUE TITLE
MonkeyRunner Error

### ISSUE THREAD

**Issue by umkhanqta** [S2-group/android-runner#54]
I was trying to run MonkeyRunner but getting following error.
Java is install.
`openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)`
but still getting this error
```
/home/umair/Android/Sdk/tools//bin/monkeyrunner /home/umair/Desktop/android-runner-master/android-runner/MonkeyRunner/jython/test/MonkeyRunner_test.py
-Djava.ext.dirs=/home/umair/Android/Sdk/tools/lib:/home/umair/Android/Sdk/tools/lib/x86_64 is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by EricZielinski** [comment]
I use openjdk 8.  Install the older version and test with that. https://github.com/S2-group/android-runner/blob/master/CONTRIBUTING.md

**Comment by umkhanqta** [comment]
thanks for the help
the older version was installed but was not set default

after installing the older version we can select the older version using this command
`sudo update-alternatives --config java`

**Comment by umkhanqta** [comment]
now getting this error

/home/umair/Android/Sdk/tools//bin/monkeyrunner /home/umair/Desktop/android-runner-master/android-runner/MonkeyRunner/jython/test/MonkeyRunner_test.py
.E....
======================================================================
ERROR: testWaitForConnectionDoubleArg (__main__.TestMonkeyRunnerArgParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/umair/Desktop/android-runner-master/android-runner/MonkeyRunner/jython/test/MonkeyRunner_test.py", line 34, in testWaitForConnectionDoubleArg
    MonkeyRunner.waitForConnection(2, '*')
PatternSyntaxException: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*
^

----------------------------------------------------------------------
Ran 6 tests in 7.700s

FAILED (errors=1)

**Comment by umkhanqta** [comment]
This fix resolves the problem of 

'Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper'

https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror

**Comment by EricZielinski** [comment]
Thanks! Consider making a PR to add that error message and link for the solution to the bottom of the Monkey README here: https://github.com/S2-group/android-runner/tree/master/MonkeyPlayer
